name: flutter_razorpay_web
description: Package for razorpay web.
version: 0.0.1
repository: https://github.com/priyaranjan12345/flutter_razorpay_web
homepage: https://fluttercompletereference.com/

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
